server:
  port: 9903

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/chrywhy/test
          searchPaths: spring-cloud/helloworldConfig
  application:
    name: service-config-server