server:
  port: 9907

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/

spring:
  application:
    name: service-feign-client

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
