server:
  port: 9904

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/

spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yb1959080058/uaps.git
          searchPaths: configFiles